// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwcppywwkbdvjmdwslbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3Y3BweXd3a2JkdmptZHdzbGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDYwMTAsImV4cCI6MjA2ODA4MjAxMH0.2rXAZMuLbDxOfHWFPBR7MtI4ewKS_GUyU1VxhkEIvmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});